version: "3.8"
services:
  pgdatabase: # host/address
    image: postgres:13
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - "7000:5432"

# test connection
#psql --host=localhost --port 7000 --username=test --dbname=ny_taxi
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin-2
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    ports:
#      - "8080:80"

# ingest data into postgres db
# python ingest_data.py --user=test --password=test --host=localhost --port=7000 --db=ny_taxi --table_name=yellow_taxi_trips --url="Nope"


